export const GET_CART_START = "GET_CART_START";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_ERROR = "GET_CART_ERROR";

export const ADD_CART_START = "ADD_CART_START";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_ERROR = "ADD_CART_ERROR";

export const REMOVE_CART_START = "REMOVE_CART_START";
export const REMOVE_CART_SUCCESS = "REMOVE_CART_SUCCESS";
export const REMOVE_CART_ERROR = "REMOVE_CART_ERROR";

export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_ERROR = "GET_IMAGE_ERROR";

export const SET_BUTTON_SUCCESS = "SET_BUTTON_SUCCESS";
export const SET_BUTTON_ERROR = "SET_BUTTON_ERROR";
